# Generated by Django 3.0.8 on 2020-08-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='verbs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eng', models.CharField(max_length=100)),
                ('fr', models.CharField(max_length=100)),
                ('img_photo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
