# Generated by Django 3.0.9 on 2020-08-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_cross'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cross',
            old_name='eng',
            new_name='word',
        ),
    ]
