# Generated by Django 3.0.9 on 2020-08-03 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200803_1344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cross',
        ),
    ]
