# Generated by Django 3.0.9 on 2020-08-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_cross'),
    ]

    operations = [
        migrations.CreateModel(
            name='cross',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100)),
            ],
        ),
    ]
