# Generated by Django 3.0.9 on 2020-08-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_cross'),
    ]

    operations = [
        migrations.AddField(
            model_name='verbs',
            name='img_url',
            field=models.URLField(default=''),
        ),
    ]
