# Generated by Django 3.0.9 on 2020-09-26 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_verbs_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verbs',
            name='img_url',
        ),
    ]
